words = [
    'PYTHON', 'JAVA', 'JAVASCRIPT', 'RUBY', 'PHP', 'TYPESCRIPT',
    'KOTLIN', 'SWIFT', 'RUST', 'SCALA', 'HASKELL', 'PERL',
    'HTML', 'CSS', 'REACT', 'ANGULAR', 'VUE', 'DJANGO',
    'FLASK', 'SPRING', 'EXPRESS', 'MONGODB', 'MYSQL', 'POSTGRESQL',
    'DOCKER', 'KUBERNETES', 'LINUX', 'WINDOWS', 'MACOS', 'GIT',
    'GITHUB', 'GITLAB', 'JENKINS', 'TERRAFORM', 'AWS', 'AZURE'
]